#!/bin/bash

# This bash runs the cmake, and make file in the build
# folder before Initializing all test cases in separate
# windows for readaility. 

cd Code/5_Build
rm -R -- */
rm *
cmake ..
make
./2_Emulator/EngineTest --gtest_output=xml:../6_TestReports/EngineTestReport.xml
./2_Emulator/GearboxTest --gtest_output=xml:../6_TestReports/GearboxTestReport.xml
cd ../6_TestReports
#Wait a while to make sure the testreports have been written
sleep 1
xunit-viewer -r .
sensible-browser --new-tab index.html
cd ..
cppcheck --enable=all .
cd 7_ScanBuild
scan-build cmake ..
scan-build -o scanbuild/ make


