@startuml
title Activity Diagram Accelerate
start
:gaspedal pressed;
if (Is engine on?) then (yes)
    if (Is gear in D or R?) then (yes)
        if (Is break pedal pressed) then (no)
        :increase speed;
else (yes)
stop
endif
else (no)
stop 
endif
else (no)
stop
endif 
stop                   
@enduml
