@startuml
title Activity Diagram Accelerate
start
:gaspedal pressed;
if (Is engine on?) then (yes)
    if (Is gear in D or R?) then (yes)
        :increase speed;
else (no)
stop 
endif
else (no)
stop
endif 
stop                   
@enduml
