@startuml
title Activity Diagram Accelerate Forward
start
:gaspedal pressed;
if (Is engine on?) then (yes)
    if (Is gear in D?) then (yes)
        if (Is break pedal pressed) then (no)
        :increase momentum;
else (no)
stop
endif
else (no)
stop 
endif
else (no)
stop
endif 
stop                   
@enduml
