@startuml
title Component Diagram

package "InputHandler" {
    [Input Handler] --> [InputHandler::CANIO]
    [InputHandler::CANIO]
}

package "Emulator"{
    [Emulator::CANIO]
    package "runVehicle" {
        [Engine] <-> [Gearbox]
    }  
    cloud "Memory"{
    [CanIn]
    [CanOut]
    }  
    
}

package "GUI" {
    [GUI] <-- [GUI::CANIO]
}

[InputHandler::CANIO] ---> CAN

[Engine] -> [CanOut]
[Gearbox]<--[CanIn]
[Gearbox] -> [CanOut]
[CanOut] -> [Emulator::CANIO]
[CanIn] <-- [Emulator::CANIO] 
[Emulator::CANIO] <-- CAN 
[Emulator::CANIO] -> CAN


[Engine] <--[CanIn]

[GUI::CANIO] <--- CAN 


@enduml