@startuml
package "Emulator"{
    [Read CAN]
    package "Process Information" {
        [State Machine] 
        [Engine]
        [Gear]
    } 
    [Send CAN]    
}
cloud "Shared Memory"{
    [input]
    [output]
}

[Input Handler] --> [Read CAN] : CAN
[input] <.. [Read CAN]

[input] ..> [State Machine]
[input] ..> [Engine]
[input] ..> [Gear]

[State Machine] ..> [output]
[Engine] ..> [output]
[Gear] ..> [output]

[output] ..> [Send CAN]

[Send CAN] --> Output : CAN

@enduml