@startuml
()AccPdl -- [CanReader]
()BrkPdl -- [CanReader]
()GearReq -- [CanReader]
()StartBtn -- [CanReader]


[Engine] <.. StartBtn: use
[Engine] <.. GearSts: use
[Engine] <.. AccPdl: use
[Engine] -- Torque


[GearBox] <.. Torque: use
[GearBox] <.. BrkPdl: use
[GearBox] <..GearReq: use
[GearBox] -- GearSts
[GearBox] -- RPM
[GearBox] -- VehicleSpeed

[CanWriter] <..GearSts: use
[CanWriter] <..RPM: use
[CanWriter] <..VehicleSpeed: use





[CanWriter]

@enduml