@startuml
title Component Diagram

package "Emulator"{
    [runCANIO]
    package "runVehicle" {
        [Engine]
        [Gearbox]
    }    
}
cloud "CANIO" {
    [readCANIO]
    [writeCANIO]
}
cloud "Memory"{
    [CanIn]
    [CanOut]
}

[Input Handler] --> [writeCANIO]
[writeCANIO] --> CAN

[runCANIO] <- [readCANIO]
[readCANIO] <- CAN
[runCANIO] -> [CanIn]

[Engine] <--[CanIn]
[Engine] <-> [Gearbox]
[Gearbox]<-[CanIn]
[Gearbox] -> [CanOut]
[CanOut] -> [writeCANIO]

CAN -> [GUI]


@enduml