@startuml
()accPdl -- [CanReader]
()BrkPdl -- [CanReader]
()gearReq -- [CanReader]
()startBtn -- [CanReader]


[Engine] <.. startBtn: use
[Engine] <.. GearSts: use
[Engine] <.. accPdl: use
[Engine] -- Torque


[GearBox] <.. Torque: use
[GearBox] <.. BrkPdl: use
[GearBox] <..gearReq: use
[GearBox] -- GearSts
[GearBox] -- RPM
[GearBox] -- vhlSpeed

[CanWriter] <..GearSts: use
[CanWriter] <..RPM: use
[CanWriter] <..vhlSpeed: use

[CanWriter]

@enduml