@startuml
title Change GearStickPosition
participant Input
participant EngineControl
participant Engine
participant Gearbox
participant Vehicle
participant Output
Input -> Gearbox : ChangeGearStickPosition(PRND)
Gearbox -> Vehicle : GetVehicleSpeed()
Gearbox <- Vehicle : VehicleSpeed
Gearbox -> Gearbox : SetGearStickPosition()


@enduml