@startuml
title Accelerate
participant Input
participant Engine
participant Gearbox
participant Output
Input -> Engine : run()
Engine <- Engine : EngineState
Engine <- Engine : setTrqFromAccPedal()


@enduml