@startuml
title Turn off engine
database Input
participant EngineControl
participant Engine
participant Gearbox
participant Vehicle
participant Output
Input -> EngineControl : StartButtonPressed()
EngineControl -> Engine : IsEngineOn()
EngineControl <- Engine : EngineState
EngineControl -> Vehicle : GetvehicleSpeed()
EngineControl <- Vehicle : vehicleSpeed
EngineControl -> Gearbox : GetgearStickPosition()
EngineControl <- Gearbox : gearStickPosition
EngineControl <- EngineControl : Decelerate()
@enduml