@startuml 
title Engine Process
database input

Engine <- input : StartBtn
Engine <- input : BrakePed

Engine -> Engine : If Engine == Off && StartBtn == 1 && BrakePedal == 100
note right of Engine : Start engine sequence is started(this.EngineSts=On)

Engine <- GearBox : GearFunc
Engine -> Engine : Else If Engine == On && GearFunc == P
note right of Engine : Turn off engine sequence is started(this.EngineSts=Off)

Engine <- input : GasPed
Engine <- GearBox : RPS
note right of Engine : Set this.EngineRPM)


@enduml