@startuml
title Change gearStickPosition
participant Input
participant Engine
participant Gearbox
participant Output
Input -> Gearbox : setGearStickPosition(PRND)
Gearbox -> Gearbox : vehicleSpeed
Gearbox -> Gearbox : brakePedal

@enduml