@startuml
title Turn off engine
database Input
participant Engine
participant Gearbox
participant Output
Input -> Engine : StartButtonPressed()
Engine <- Engine : EngineState
Engine -> Gearbox : GetEngineRPS()
Engine <- Gearbox : EngineRPS
Engine -> Gearbox : GetGearStickPosition()
Engine <- Gearbox : gearStickPosition
Engine <- Engine : Decelerate()
@enduml