@startuml
title Change gearStickPosition
participant Input
participant Engine
participant Gearbox
participant Vehicle
participant Output
Input -> Gearbox : ChangegearStickPosition(PRND)
Gearbox -> Vehicle : GetvehicleSpeed()
Gearbox <- Vehicle : vehicleSpeed
Gearbox -> Gearbox : SetgearStickPosition()

@enduml