#!/bin/bash

# This bash runs the cmake, and make file in the build
# folder before starting up the main thread in a separate 
# terminal window and thereafter starting the input handler
# in the first terminal window. 

cd 5_Build
rm -R -- */
rm *
cmake ..
make
gnome-terminal -- ./2_Emulator/EmulatorMain
gnome-terminal -- ./3_GUI/app/avic/avic -c vcan0
./1_InputHandler/InputHandler_Main 











